version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: script/stop_server.sh
      timeout: 3600
      runas: root     
      
  AfterInstall:
    - location: script/start_server.sh
      timeout: 3600
      runas: root
      
  ValidateService:
    - location: script/status_server.sh
      timeout: 3600
      runas: root


