version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/stop_server
      timeout: 3600
     
  AfterInstall:
    - location: scripts/start_server
      timeout: 3600
  ValidateService:
    - location: scripts/status_server
      timeout: 3600
      runas: root


